management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      user-service:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50  # 50% failure
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true  # after 5 sec open to half open
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3  # after 3 call success close the circuit or else Open again
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED # TIME_BASED

#See the status in http://localhost:8080/actuator/health